server:
  port: 8073
  servlet:
    context-path: /year&semester

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LVTN_SchoolYear&Semester-service?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 12345
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
