export const ethnicGroups = [
    { id: '01', name: 'Kinh' },
    { id: '02', name: 'Tày' },
    { id: '03', name: 'Thái' },
    { id: '04', name: 'Hoa' },
    { id: '05', name: 'Khmer' },
    { id: '06', name: 'Mường' },
    { id: '07', name: 'Nùng' },
    { id: '08', name: 'Hmông' },
    { id: '09', name: 'Dao' },
    { id: '10', name: 'Ngai' },
    { id: '11', name: 'Sán Chảy' },
    { id: '12', name: 'Chăm' },
    { id: '13', name: 'San Diu' },
    { id: '14', name: 'Vân kiều' },
    { id: '15', name: 'Tho' },
    { id: '16', name: 'Giay' },
    { id: '17', name: 'Cờ Tu' },
    { id: '18', name: 'Khơ Mú' },
    { id: '19', name: 'Ta Oi' },
    { id: '20', name: 'Khang' },
    { id: '21', name: 'Lào' },
    { id: '22', name: 'La Chi' },
    { id: '23', name: 'Phu La' },
    { id: '24', name: 'Lo Lo' },
    { id: '25', name: 'Pha Then' },
    { id: '26', name: 'Co Lao' },
    { id: '27', name: 'Bo Y' },
    { id: '28', name: 'Si La' },
    { id: '29', name: 'Pu Peo' },
    { id: '30', name: 'DT Khác' },
    { id: '31', name: 'Xinh mun' },
    { id: '32', name: 'Chu ru' },
    { id: '33', name: 'Thượng' },
    { id: '34', name: 'La hú' },
    { id: '35', name: 'Mông' },
    { id: '36', name: 'Lự' },
    { id: '37', name: 'Jrai' },
    { id: '38', name: 'Hán' },
    { id: '39', name: 'Chút' },
    { id: '40', name: 'Mảng' },
    { id: '41', name: 'Êđê' },
    { id: '42', name: 'Cao Lan' },
    { id: '43', name: 'La ha' },
    { id: '44', name: 'Côông' },
    { id: '45', name: 'Xtiêng' },
    { id: '49', name: 'Rơ măm' },
    { id: '50', name: 'Ơ đu' },
    { id: '52', name: 'Ra glai' },
    { id: '54', name: 'Pacô' },
    { id: '55', name: 'Pahy' },
];

export const nationalities = [
    { id: '001', name: 'Việt Nam' },
    { id: '002', name: 'Argentina' },
    { id: '003', name: 'Cộng hoà Azerbaijan' },
    { id: '004', name: 'Ai cập' },
    { id: '005', name: 'Iceland' },
    { id: '006', name: 'Ireland' },
    { id: '007', name: 'Albania' },
    { id: '008', name: 'Algeria' },
    { id: '010', name: 'Cộng hòa Armenia' },
    { id: '011', name: 'Angola' },
    { id: '012', name: 'Áo' },
    { id: '013', name: 'Afghanistan' },
    { id: '014', name: 'A-rập Xê-út' },
    { id: '015', name: 'Ấn Độ' },
    { id: '016', name: 'Bangladesh' },
    { id: '017', name: 'Bolivia' },
    { id: '018', name: 'Cộng hòa Bosna và Hercegovina' },
    { id: '019', name: 'Bồ Đào Nha' },
    { id: '020', name: 'Ba Lan' },
    { id: '021', name: 'Cộng hòa Belarus' },
    { id: '022', name: 'Cộng hòa Botswana' },
    { id: '023', name: 'Bỉ' },
    { id: '024', name: 'Brazil' },
    { id: '025', name: 'Brunây' },
    { id: '026', name: 'Vương quốc Bhutan' },
    { id: '027', name: 'Cộng hòa Burkina Faso' },
    { id: '028', name: 'Cộng hòa Bungari' },
    { id: '029', name: 'Cam-pu-chia' },
    { id: '030', name: 'Colombia' },
    { id: '031', name: 'Cộng hòa Dân chủ Congo' },
    { id: '032', name: 'Nhà nước Kuwait' },
    { id: '033', name: 'Cộng hòa Costa Rica' },
    { id: '034', name: 'Kazakhstan' },
    { id: '035', name: 'Cộng hòa Cameroon' },
    { id: '036', name: 'Canada' },
    { id: '037', name: 'Cộng hòa Kyrgyzstan' },
    { id: '038', name: 'Cộng hòa Séc' },
    { id: '039', name: 'CHDCND Lào' },
    { id: '040', name: 'Cộng hòa Dân chủ Nhân dân Triều Tiên' },
    { id: '041', name: 'Chi lê' },
    { id: '042', name: 'Cộng hòa Nhân dân Trung Hoa' },
    { id: '043', name: 'Croatia' },
    { id: '044', name: 'Cuba' },
    { id: '045', name: 'Cộng hòa Dăm-bi-a' },
    { id: '046', name: 'Cộng hòa Zimbabwe' },
    { id: '047', name: 'Đài loan' },
    { id: '048', name: 'Đaia' },
    { id: '049', name: 'Đan Mạch' },
    { id: '050', name: 'Đức' },
    { id: '051', name: 'Et-tô-ni' },
    { id: '052', name: 'Cộng hòa Estonia' },
    { id: '053', name: 'Ecuador' },
    { id: '054', name: 'Cộng hòa Dân chủ Liên bang Ethiopia' },
    { id: '055', name: 'Cộng hòa Gambia' },
    { id: '056', name: 'Cộng hòa Ghi Nê' },
    { id: '057', name: 'Cộng hòa Georgia' },
    { id: '058', name: 'Hà lan' },
    { id: '059', name: 'Hàn Quốc' },
    { id: '060', name: 'Hồng Công' },
    { id: '061', name: 'Hungary' },
    { id: '062', name: 'Hy Lạp' },
    { id: '063', name: 'Indonesia' },
    { id: '064', name: 'Iraq' },
    { id: '065', name: 'Cộng hòa Hồi giáo Iran' },
    { id: '066', name: 'Ý' },
    { id: '067', name: 'Israel' },
    { id: '069', name: 'Cộng hòa Kenya' },
    { id: '070', name: 'Kirgixtan' },
    { id: '071', name: 'Cộng hòa Độc lập và Chủ quyền Kiribati' },
    { id: '072', name: 'Cộng hòa Latvia' },
    { id: '073', name: 'Liên bang Nga' },
    { id: '074', name: 'Liên xô cũ' },
    { id: '075', name: 'Cộng hòa Liban' },
    { id: '076', name: 'Cộng hòa Liberia' },
    { id: '077', name: 'Libya' },
    { id: '078', name: 'Cộng hòa Litva' },
    { id: '079', name: 'Luc-xem-bua' },
    { id: '080', name: 'Cộng hòa Mozambique' },
    { id: '081', name: 'Cộng hòa Moldova' },
    { id: '082', name: 'Môn-đa-vi' },
    { id: '083', name: 'Thân vương quốc Monaco' },
    { id: '084', name: 'Mông cổ' },
    { id: '085', name: 'Mexico' },
    { id: '086', name: 'Madagascar' },
    { id: '087', name: 'Malaysia' },
    { id: '088', name: 'Cộng hòa Mali' },
    { id: '089', name: 'Cộng hòa Maldives' },
    { id: '090', name: 'Cộng hòa Mauritius' },
    { id: '092', name: 'Liên bang Micronesia' },
    { id: '093', name: 'Mỹ' },
    { id: '094', name: 'Myanmar' },
    { id: '095', name: 'Na Uy' },
    { id: '096', name: 'Nam phi' },
    { id: '097', name: 'Nam Tư' },
    { id: '098', name: 'Namibia' },
    { id: '099', name: 'Nepal' },
    { id: '100', name: 'Nhật bản' },
    { id: '101', name: 'Cộng hòa Nicaragua' },
    { id: '102', name: 'Nigiê' },
    { id: '103', name: 'Nigeria' },
    { id: '104', name: 'New Zealand' },
    { id: '105', name: 'Vương quốc Oman' },
    { id: '106', name: 'Australia' },
    { id: '107', name: 'Pakistan' },
    { id: '108', name: 'Pa-na-ma' },
    { id: '109', name: 'Quốc gia Độc lập Pa-pua Niu Ghi-nê' },
    { id: '110', name: 'Paraguay' },
    { id: '111', name: 'Peru' },
    { id: '112', name: 'Pháp' },
    { id: '113', name: 'Phần Lan' },
    { id: '114', name: 'Cộng hòa Fiji' },
    { id: '115', name: 'Philippines' },
    { id: '116', name: 'Nhà nước Qatar' },
    { id: '117', name: 'Quần đảo Cook' },
    { id: '118', name: 'Cộng hòa Quần đảo Marshall' },
    { id: '119', name: 'Liên bang Quần đảo Solomon' },
    { id: '120', name: 'Cộng hòa Rwanda' },
    { id: '121', name: 'Rumani' },
    { id: '122', name: 'Somalia' },
    { id: '123', name: 'Cộng hòa Tchad' },
    { id: '124', name: 'Syria' },
    { id: '126', name: 'Slovenia' },
    { id: '127', name: 'Cộng hòa Xã hội Chủ nghĩa Dân chủ Sri Lanka' },
    { id: '128', name: 'Vương quốc Tonga' },
    { id: '129', name: 'Tây Ban Nha' },
    { id: '130', name: 'Thụy Sĩ' },
    { id: '131', name: 'Thái Lan' },
    { id: '132', name: 'Trung Quốc' },
    { id: '133', name: 'Tu-ynidi' },
    { id: '134', name: 'Turkmenistan' },
    { id: '135', name: 'Tuy-ni-di' },
    { id: '136', name: 'Turkmenistan' },
    { id: '137', name: 'Uzbekistan' },
    { id: '138', name: 'Việt Nam' },
    { id: '139', name: 'Vanuatu' },
];
