server:
  port: 8080
  servlet:
    context-path: /attendance

app:
  services:
    teacher: http://localhost:8072/teacher

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LVTN_Attendance-service?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 12345
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
