server:
  port: 8075
  servlet:
    context-path: /relationship


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/LVTN_Relationship-service?createDatabaseIfNotExist=true
    driverClassName: com.mysql.cj.jdbc.Driver
    password: 12345
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    show-sql: false
